// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod rate_limit {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum RateLimitRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

/// A rate-limit check request sent by a client over TCP.
pub struct RateLimitRequest<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RateLimitRequest<'a> {
  type Inner = RateLimitRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RateLimitRequest<'a> {
  pub const VT_CLIENT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_RESOURCE: flatbuffers::VOffsetT = 6;
  pub const VT_COST: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RateLimitRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RateLimitRequestArgs<'args>
  ) -> flatbuffers::WIPOffset<RateLimitRequest<'bldr>> {
    let mut builder = RateLimitRequestBuilder::new(_fbb);
    builder.add_cost(args.cost);
    if let Some(x) = args.resource { builder.add_resource(x); }
    if let Some(x) = args.client_id { builder.add_client_id(x); }
    builder.finish()
  }


  /// Opaque identifier for the caller (IP, user-id, API key, …)
  #[inline]
  pub fn client_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RateLimitRequest::VT_CLIENT_ID, None).unwrap()}
  }
  /// The resource being accessed, e.g. "/api/v1/orders"
  #[inline]
  pub fn resource(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RateLimitRequest::VT_RESOURCE, None)}
  }
  /// How many units of capacity to consume (default 1)
  #[inline]
  pub fn cost(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(RateLimitRequest::VT_COST, Some(1)).unwrap()}
  }
}

impl flatbuffers::Verifiable for RateLimitRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("client_id", Self::VT_CLIENT_ID, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("resource", Self::VT_RESOURCE, false)?
     .visit_field::<u32>("cost", Self::VT_COST, false)?
     .finish();
    Ok(())
  }
}
pub struct RateLimitRequestArgs<'a> {
    pub client_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub resource: Option<flatbuffers::WIPOffset<&'a str>>,
    pub cost: u32,
}
impl<'a> Default for RateLimitRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    RateLimitRequestArgs {
      client_id: None, // required field
      resource: None,
      cost: 1,
    }
  }
}

pub struct RateLimitRequestBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RateLimitRequestBuilder<'a, 'b> {
  #[inline]
  pub fn add_client_id(&mut self, client_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RateLimitRequest::VT_CLIENT_ID, client_id);
  }
  #[inline]
  pub fn add_resource(&mut self, resource: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RateLimitRequest::VT_RESOURCE, resource);
  }
  #[inline]
  pub fn add_cost(&mut self, cost: u32) {
    self.fbb_.push_slot::<u32>(RateLimitRequest::VT_COST, cost, 1);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RateLimitRequestBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RateLimitRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RateLimitRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, RateLimitRequest::VT_CLIENT_ID,"client_id");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RateLimitRequest<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RateLimitRequest");
      ds.field("client_id", &self.client_id());
      ds.field("resource", &self.resource());
      ds.field("cost", &self.cost());
      ds.finish()
  }
}
pub enum RateLimitResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Server response to every RateLimitRequest.
pub struct RateLimitResponse<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RateLimitResponse<'a> {
  type Inner = RateLimitResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> RateLimitResponse<'a> {
  pub const VT_ALLOWED: flatbuffers::VOffsetT = 4;
  pub const VT_REMAINING: flatbuffers::VOffsetT = 6;
  pub const VT_RETRY_AFTER_MS: flatbuffers::VOffsetT = 8;
  pub const VT_REASON: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    RateLimitResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RateLimitResponseArgs<'args>
  ) -> flatbuffers::WIPOffset<RateLimitResponse<'bldr>> {
    let mut builder = RateLimitResponseBuilder::new(_fbb);
    builder.add_retry_after_ms(args.retry_after_ms);
    builder.add_remaining(args.remaining);
    if let Some(x) = args.reason { builder.add_reason(x); }
    builder.add_allowed(args.allowed);
    builder.finish()
  }


  /// true  → request is allowed to proceed
  /// false → request must be dropped / retried
  #[inline]
  pub fn allowed(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(RateLimitResponse::VT_ALLOWED, Some(false)).unwrap()}
  }
  /// Remaining capacity after this request (tokens, slots, …)
  #[inline]
  pub fn remaining(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(RateLimitResponse::VT_REMAINING, Some(0)).unwrap()}
  }
  /// How many milliseconds the caller should wait before retrying.
  /// 0 when allowed = true.
  #[inline]
  pub fn retry_after_ms(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(RateLimitResponse::VT_RETRY_AFTER_MS, Some(0)).unwrap()}
  }
  /// Human-readable explanation of the decision.
  #[inline]
  pub fn reason(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(RateLimitResponse::VT_REASON, None)}
  }
}

impl flatbuffers::Verifiable for RateLimitResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<bool>("allowed", Self::VT_ALLOWED, false)?
     .visit_field::<i64>("remaining", Self::VT_REMAINING, false)?
     .visit_field::<i64>("retry_after_ms", Self::VT_RETRY_AFTER_MS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("reason", Self::VT_REASON, false)?
     .finish();
    Ok(())
  }
}
pub struct RateLimitResponseArgs<'a> {
    pub allowed: bool,
    pub remaining: i64,
    pub retry_after_ms: i64,
    pub reason: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for RateLimitResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    RateLimitResponseArgs {
      allowed: false,
      remaining: 0,
      retry_after_ms: 0,
      reason: None,
    }
  }
}

pub struct RateLimitResponseBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RateLimitResponseBuilder<'a, 'b> {
  #[inline]
  pub fn add_allowed(&mut self, allowed: bool) {
    self.fbb_.push_slot::<bool>(RateLimitResponse::VT_ALLOWED, allowed, false);
  }
  #[inline]
  pub fn add_remaining(&mut self, remaining: i64) {
    self.fbb_.push_slot::<i64>(RateLimitResponse::VT_REMAINING, remaining, 0);
  }
  #[inline]
  pub fn add_retry_after_ms(&mut self, retry_after_ms: i64) {
    self.fbb_.push_slot::<i64>(RateLimitResponse::VT_RETRY_AFTER_MS, retry_after_ms, 0);
  }
  #[inline]
  pub fn add_reason(&mut self, reason: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(RateLimitResponse::VT_REASON, reason);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RateLimitResponseBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RateLimitResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<RateLimitResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for RateLimitResponse<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("RateLimitResponse");
      ds.field("allowed", &self.allowed());
      ds.field("remaining", &self.remaining());
      ds.field("retry_after_ms", &self.retry_after_ms());
      ds.field("reason", &self.reason());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `RateLimitRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rate_limit_request_unchecked`.
pub fn root_as_rate_limit_request(buf: &[u8]) -> Result<RateLimitRequest, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<RateLimitRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `RateLimitRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_rate_limit_request_unchecked`.
pub fn size_prefixed_root_as_rate_limit_request(buf: &[u8]) -> Result<RateLimitRequest, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<RateLimitRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `RateLimitRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rate_limit_request_unchecked`.
pub fn root_as_rate_limit_request_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RateLimitRequest<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<RateLimitRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `RateLimitRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_rate_limit_request_unchecked`.
pub fn size_prefixed_root_as_rate_limit_request_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<RateLimitRequest<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<RateLimitRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a RateLimitRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `RateLimitRequest`.
pub unsafe fn root_as_rate_limit_request_unchecked(buf: &[u8]) -> RateLimitRequest {
  flatbuffers::root_unchecked::<RateLimitRequest>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed RateLimitRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `RateLimitRequest`.
pub unsafe fn size_prefixed_root_as_rate_limit_request_unchecked(buf: &[u8]) -> RateLimitRequest {
  flatbuffers::size_prefixed_root_unchecked::<RateLimitRequest>(buf)
}
#[inline]
pub fn finish_rate_limit_request_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<RateLimitRequest<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_rate_limit_request_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<RateLimitRequest<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod rate_limit

